// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbshfbodqsuvyjtugygj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indic2hmYm9kcXN1dnlqdHVneWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjUyNjYsImV4cCI6MjA3MTkwMTI2Nn0.9VjvkWkRaSI-MvCc7h2LHL5sCIdMo5wOqrt9Pfhb0hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});